### ISSUE TITLE
Training efficiency about deep shallow models

### ISSUE THREAD

**Issue by NonvolatileMemory** [jungokasai/deep-shallow#5]
Hi jungo!

I have a question about the training efficiency of 12-1 transformer model. It seems the training bottleneck will be the encoder part and so that when we do decoder computation such gpu resource will be waste a lot part.

Does my understanding right?

**Comment by jungokasai** [comment]
For inference, an encoder layer is much less costly than a decoder layer because of the encoder's parallel property. For training, I think they should be similar because all output sequences are already given. An encoder layer should be slightly lighter though since a decoder layer would have both cross and causal attention. So I suspect that the training efficiency for  12-1 and 6-6 transformers should be very similar.

**Comment by NonvolatileMemory** [comment]
Hi jungo, thx for your kindly reply!

But I don't agree the training one.... 
I test an extreme case with 60 enc 6 dec model, and the gpu situation is following:

![84f9ee48569dc917a1b0d1a625facb1](https://user-images.githubusercontent.com/23712512/162683488-00ad125b-940f-4b27-acb5-6be25b860b2b.png)
![0ffce842379eba40e77c64215d3e0bf](https://user-images.githubusercontent.com/23712512/162683521-5fb74e41-4b9e-4dcf-81aa-3737e3e9a97c.png)

as you can seen, high gpu memory occupation but low gpu usage, I think that because the input sentence/token(s) num are dominated by enc part, when gpu compute dec part, the resource will be oversupply

**Comment by jungokasai** [comment]
Huh, that's interesting. So you tried 6-60 as well and saw a very different level of memory overhead? Also, this can depend on the MT language pair (or non-MT tasks). It's possible that the source language is much longer than the target. Which dataset are you running this on?
